name: Deploy Lambda Function

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        run: |
          aws ecr get-login-password --region ap-southeast-2 | docker login --username AWS --password-stdin public.ecr.aws/z4c0m7a6/credit-score-lambda/credit-score-lambda:latest

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: public.ecr.aws/z4c0m7a6/credit-score-lambda
          ECR_REPOSITORY: credit-score-lambda
          IMAGE_TAG: latest
        run: |
          docker build --platform linux/amd64 -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update Lambda function with new image
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.CREDIT_AI_LAMBDA_ARN }} \
            --image-uri public.ecr.aws/z4c0m7a6/credit-score-lambda/credit-score-lambda:latest
